spring.application.name=ohunter_backend-backend

jwt.secret=verysecretkeyverysecretkeyverysecretkey
jwt.expiration=86400000

# MySQL DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/ohunter
spring.datasource.username=root
spring.datasource.password=rudra@18

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect